-- Thêm POKER vào GameType enum.
ALTER TABLE `Game` MODIFY COLUMN `key` ENUM('SLOT', 'DICE', 'FISH', 'ROULETTE', 'POKER') NOT NULL;
ALTER TABLE `GameRound` MODIFY COLUMN `game` ENUM('SLOT', 'DICE', 'FISH', 'ROULETTE', 'POKER') NOT NULL;
